language: node_js
node_js: "10"

# Cache node_modules for faster setup
cache:
  directories:
    - node_modules
    - "$HOME/.npm"

# Install node_modules
install:
  - npm ci

# Build the site
script:
  - npm run build

# Deploy to Github Pages
# See https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  fqdn: stenci.la
  on:
    branch: master
